# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

theme: minima
url: "https://yhsmedia.github.io"
baseurl: "/preschool"

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : SWBC Preschool
author :
  name : Bruce Harrison
  email : 
  feedburner : nil

# NOTE: Replacing this next line with your own URL
production_url : https://yhsmedia.github.io/preschool/

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

minima:
  hide_share_links: true
  hide_site_feed_link: true
    - index.md
    - pages/cc_teacher_schedule.md
    - pages/cc_lessons/index.md
  
